"""Add missing columns to repositories and users tables

Revision ID: b271711dded4
Revises: 127886dec6fc
Create Date: 2025-08-30 21:48:35.425876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b271711dded4'
down_revision: Union[str, Sequence[str], None] = '127886dec6fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('github_id', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('name', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('description', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.add_column('repositories', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_repositories_github_id'), 'repositories', ['github_id'], unique=True)
    op.create_foreign_key(None, 'repositories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_index(op.f('ix_repositories_github_id'), table_name='repositories')
    op.drop_column('repositories', 'updated_at')
    op.drop_column('repositories', 'user_id')
    op.drop_column('repositories', 'is_private')
    op.drop_column('repositories', 'description')
    op.drop_column('repositories', 'name')
    op.drop_column('repositories', 'github_id')
    # ### end Alembic commands ###
